<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Root [<!ELEMENT Root (Element3, Element4, Element5)>

<!ELEMENT Element1 EMPTY>
<!ATTLIST Element1 id ID #REQUIRED>

<!ELEMENT Element2 EMPTY>
<!ATTLIST Element2 id ID #REQUIRED>

<!ELEMENT Element4 EMPTY>
<!ATTLIST Element4 id ID #REQUIRED>

<!ELEMENT Element3 (#PCDATA | Element2  | Element1 | Element4)*>

<!ELEMENT Element5 EMPTY>
<!ATTLIST Element5 id ID #REQUIRED>
]>
<Root>
    <Element3>
        <!--ici on peut avoir ces trois éléments au choix  (un, deux d'entre eux ou les trois)-->
        <Element2 id ='IM'></Element2>
        <Element1 id = 'j57' ></Element1>
        <Element4 id ='id942' ></Element4>
    </Element3>   
    <Element4 id ='gid50'></Element4>
    <Element5 id ='fr'></Element5>
</Root>




